# -*- coding: utf-8 -*-
"""constants

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L-xy2_MKOjeq3e1LYTpWZRFPUVc1s5J6
"""

REPLICATE_MODEL = "replicate/llama-2-70b-chat:2c1608e18606fad2812020dc541930f2d0495ce32eee50074220b87300bc16e1"
PROMPT_TEMPLATE = """You are a helpful support chatbot having a conversation with {user_name}.
    Follow these 3 steps:
    1. Read the context below
    2. Answer the question only using the context information
    3. Show the source for your answers

    Context : {context}
    User Question: {question}

    If you don't know the answer, just say you don't know. Do NOT try to make up an answer. If the question is
    not related to the context, politely respond that you are tuned to only answer questions that are related to
    the context. Use as much detail as possible when responding.
    Also if the question is hi, politely reply as Hello! I am your helpful assistant. How may I assist you today?"""

URLS = ["https://giki.edu.pk/",
        "https://giki.edu.pk/vision-and-mission/",
        "https://giki.edu.pk/institute/",
        "https://giki.edu.pk/academics/office-of-admission-examination/",
        "https://admissions.giki.edu.pk/Home/Index",
        "https://giki.edu.pk/admissions/admissions-undergraduates/ugradhow-to-apply/",
        "https://giki.edu.pk/admissions/admissions-undergraduates/ugrad-fees-and-expenses/",
        "https://giki.edu.pk/admissions/admissions-undergraduates/",
        "https://giki.edu.pk/contact-us-main/",
        "https://giki.edu.pk/admissions/admissions-undergraduates/",
        "https://giki.edu.pk/admissions/admissions-undergraduates/ugrad-aid-scholarships/",
        "https://giki.edu.pk/admissions/admissions-graduate/",
        "https://giki.edu.pk/admissions/admissions-graduate/grad-aid-scholarships/"
]